### ISSUE TITLE
li:nth-last-child(-n+3) parse  error 

### ISSUE THREAD

**Issue by noyobo** [mdevils/css-selector-parser#28]
```js
import {createParser} from 'css-selector-parser';

const parse = createParser();
const parsed = parse('li:nth-last-child(-n+3)');
// https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child
```
```js
 ParserError: css-selector-parser parse error: Formula parse error. Pos: 19.

       5 |   it('case', function () {
       6 |     const parser = createParser({
    >  7 |       syntax: 'progressive',
         |                    ^
       8 |     });
       9 |     const parsed = parser('li:nth-last-child(-n+3)');

      at fail (node_modules/.pnpm/css-selector-parser@2.2.2/node_modules/css-selector-parser/lib/parser.js:94:21)
      at assert (node_modules/.pnpm/css-selector-parser@2.2.2/node_modules/css-selector-parser/lib/parser.js:101:20)
      at parseNumber (node_modules/.pnpm/css-selector-parser@2.2.2/node_modules/css-selector-parser/lib/parser.js:350:
```

**Comment by mdevils** [comment]
@noyobo Thanks for reporting! Fixed in `2.3.2`.
